version: "3.8"
services:
  blogs-api:
    build: .
    image: blogs-api:latest
    container_name: blogs-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
